name: goal_pose_multitask
task_name: pickNplace_goal_pose
dataset_name: pickNplace_lfv
output_name: pickNplace_lfv_goal_pose
instruction: "Place the banana on the plate"

shape_meta:
  obs:
    agent_pos:
      shape: [7]
      type: low_dim
    lang_token_embs:
      shape: [1, 1024]
      type: low_dim
    pc_manipulated:
      shape: [256, 3]
      type: point_cloud
    pc_target:
      shape: [256, 3]
      type: point_cloud
  goal:
    shape: [9]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.lfv_dataset.GoalPoseSE3Dataset
  data_dirs:
    - "/media/ljian/lj/data_3d/pickNplace_lfv"
  pred_horizon: 16
  obs_horizon: 1
  action_horizon: 8
  use_lang_emb: true
  missing_lang_emb: zero
  num_pts: 256
  val_ratio: 0.1
  intrinsics_source: "depth_intrinsics_original"
